[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# auto-detect solc
auto_detect_solc = true

[rpc_endpoints]
# eth-public = { url = "https://eth.public-rpc.com/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config